/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:blah-blah-blah",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_asfdsdfdf",
    "aws_user_pools_web_client_id": "asdfasdfsdfsd",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://asdfsdfsdfds/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
